version: 2.1
orbs:
  clj:
    executors:
      lein_browsers:
        docker:
          - image: circleci/clojure:lein-2.8.1-node-browsers
        working_directory: ~/repo
        environment:
          LEIN_ROOT: "true"
          # Customize the JVM maximum heap limit
          JVM_OPTS: -Xmx3200m
    commands:
      test-clj:
        description: "Build and test CLJ projects"
        steps:
          - checkout

          # Download and cache dependencies
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "project.clj" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

          - run:
              command: lein test

          - save_cache:
              paths:
                - ~/.m2
              key: v1-dependencies-{{ checksum "project.clj" }}

jobs:
  build:
    # Note that this is a clj orb, not a cljs one.
    executor: clj/lein_browsers
    steps:
      - clj/test-clj
